#define PI 3.14159265
#define TWO_PI 6.28318530

#define TILE_SIZE 48
#define COLS 20
#define ROWS 13

#define MINIMAP_SCALE_FACTOR 0.2
#define WINDOW_WIDTH (COLS * TILE_SIZE)
#define WINDOW_HEIGHT (ROWS * TILE_SIZE)

#define TEXTURE_WIDTH 48
#define TEXTURE_HEIGHT 48

#define FOV_ANGLE 60 * (PI / 180)
#define PROJECTION_THICKNESS 1
#define NUM_RAYS (WINDOW_WIDTH / PROJECTION_THICKNESS)
#define CORRECT_FISH_EYE_EFFECT 1

#define FPS 30
#define FRAME_TARGET_TIME (1000 / FPS)
